(function(){
'use strict';
const DATA={
A1:[['My day','Tell me about your normal day.','Opowiedz o swoim typowym dniu.',['What time do you get up?','What do you do in the morning?','What do you do after school/work?'],['I usually…','Then I…','I like… because…'],'30-second challenge: describe your day without stopping.'],['My favourite place','Describe a place you like.','Opisz miejsce, które lubisz.',['Where is it?','What is it like?','Why do you like it?'],['It is near…','There is…','I like it because…'],'Add three details: people, things and feelings.'],['Everyday role-play','You are in a café. Order a drink and something to eat.','Jesteś w kawiarni. Zamów napój i coś do jedzenia.',['Greet the server.','Order politely.','Ask the price.'],['Can I have…?','I would like…','How much is…?'],'Role-play it twice: first slowly, then naturally.']],
A2:[['Weekend plans','Talk about your plans for the weekend.','Opowiedz o swoich planach na weekend.',['What are you going to do?','Who will you spend time with?','What might change?'],['I am going to…','I would like to…','Maybe I will…'],'Speak for 45 seconds and include one alternative plan.'],['A recent experience','Describe something you did recently.','Opisz coś, co ostatnio zrobiłeś/aś.',['Where did you go?','Who were you with?','What happened?'],['Last week…','Then…','It was… because…'],'Tell the story in order: beginning → middle → result.'],['Giving advice','A friend has too much work. Give useful advice.','Znajomy ma za dużo pracy. Udziel mu dobrej rady.',['What should they do first?','What could they stop doing?','What must they avoid?'],['You should…','You could…','You don’t have to…'],'Give two solutions and explain which one is better.']],
B1:[['Problem solving','Your train is cancelled before an important meeting. What do you do?','Pociąg został odwołany przed ważnym spotkaniem. Co robisz?',['What is your first step?','What alternatives are there?','How do you explain the situation?'],['I would…','Another option would be…','The best solution is…'],'Give a solution, a reason and a possible problem.'],['Compare two choices','Would you rather study online or in person?','Wolisz uczyć się online czy stacjonarnie?',['What is the main advantage?','What is the drawback?','Who would benefit most?'],['On the one hand…','However…','It depends on…'],'Give a balanced answer before choosing a side.'],['Story challenge','Start with: “I didn’t expect anything unusual to happen that day…”','Zacznij od: „Nie spodziewałem/am się, że tego dnia wydarzy się coś niezwykłego…”',['What happened?','How did you react?','How did it end?'],['At first…','Suddenly…','In the end…'],'Tell a 60-second story with at least three past-tense verbs.']],
B2:[['Opinion + counterargument','Is working from home better than working in an office?','Czy praca z domu jest lepsza niż praca w biurze?',['What is your position?','What is your strongest reason?','What might an opponent say?'],['In my view…','The main reason is…','However, some people argue…'],'Give one argument, one counterargument and your response.'],['Matura-style discussion','Should young people be required to do volunteer work?','Czy młodzi ludzie powinni mieć obowiązek wolontariatu?',['What are the benefits?','What are the risks?','What would be a fair policy?'],['It could be argued that…','A possible drawback is…','On balance…'],'Speak for 90 seconds. Avoid repeating the same linking phrase.'],['Decision meeting','Your group has money for only one project: a sports area, library or green space. Decide.','Wasza grupa ma pieniądze tylko na jeden projekt: obiekt sportowy, bibliotekę lub teren zielony. Podejmijcie decyzję.',['Which option helps most people?','What evidence would you want?','Why reject the other options?'],['I propose…','Taking into account…','I see your point, but…'],'Reach a clear decision and justify it.']],
C1:[['Nuanced opinion','Does social media improve communication? Give a qualified answer.','Czy media społecznościowe poprawiają komunikację? Udziel wyważonej odpowiedzi.',['What evidence supports your view?','What limitation should you mention?','When might the opposite be true?'],['To some extent…','This tends to…','That said…','It would be misleading to say…'],'Replace one absolute claim with a more precise one.'],['Critical response','Someone says: “People who work longer are always more successful.” Respond.','Ktoś mówi: „Ludzie, którzy pracują dłużej, zawsze odnoszą większe sukcesy”. Odpowiedz.',['What assumption is being made?','What evidence is missing?','What alternative explanation exists?'],['That depends on…','The claim assumes…','A more plausible explanation may be…'],'Challenge the claim without simply saying it is wrong.'],['Presentation challenge','Explain one skill that schools should teach more effectively.','Wyjaśnij, jakiej umiejętności szkoły powinny uczyć skuteczniej.',['Why does it matter?','How should it be taught?','How could success be measured?'],['The key issue is…','For example…','This suggests that…','Ultimately…'],'Give a 2-minute mini-presentation with a clear opening and conclusion.']],
C2:[['Advanced debate','Should governments regulate algorithms that influence what people see online?','Czy rządy powinny regulować algorytmy wpływające na to, co widzimy w internecie?',['What should regulation achieve?','What unintended consequences could occur?','Where should responsibility lie?'],['The underlying issue is…','One could argue…','A potential consequence is…','Nevertheless…'],'Present both sides, then defend a nuanced position.'],['Counterfactual thinking','Imagine that smartphones had never been invented. How would society be different?','Wyobraź sobie, że smartfony nigdy nie zostały wynalezione. Jak społeczeństwo byłoby inne?',['What would people do differently?','What might have developed instead?','What would we gain or lose?'],['Had… existed…','We might have…','It is conceivable that…'],'Use at least one third conditional and one mixed conditional.'],['Impromptu argument','Choose a side: convenience is more valuable than privacy.','Wybierz stanowisko: wygoda jest ważniejsza niż prywatność.',['Define the key terms.','Build the strongest opposing argument.','Explain your final judgement.'],['The distinction lies in…','Granted…','Even so…','On balance…'],'Speak for 2 minutes without reading notes. Finish with a precise conclusion.']]
};
function esc(s){return s.replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));}
function render(){const host=document.getElementById('speaking'), out=document.getElementById('speak'), filters=document.getElementById('sf');if(!host||!out||!filters||host.dataset.enhanced)return;host.dataset.enhanced='1';filters.innerHTML='';
['ALL','A1','A2','B1','B2','C1','C2'].forEach((level,i)=>{const b=document.createElement('button');b.textContent=level;b.className=i===0?'active':'';b.onclick=()=>{filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(level)};filters.appendChild(b)});
function draw(level){const rows=[];Object.keys(DATA).forEach(l=>{if(level==='ALL'||l===level)DATA[l].forEach((a,i)=>rows.push([l,i,a]));});out.innerHTML=rows.map(([l,i,a],n)=>`<article class="card"><div class="tag">${l} • SPEAKING</div><h2>${esc(a[0])}</h2><p><strong>Task / Zadanie:</strong> ${esc(a[1])}</p><div class="pl">${esc(a[2])}</div><div class="callout"><strong>Questions / Pytania</strong><ol>${a[3].map(q=>`<li>${esc(q)}</li>`).join('')}</ol></div><p><strong>Useful language / Przydatne zwroty</strong></p><div class="pl">${a[4].map(x=>esc(x)).join(' • ')}</div><p><strong>Challenge / Wyzwanie:</strong> ${esc(a[5])}</p><div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:12px"><button class="btn primary" data-timer="${n}">⏱️ 60s</button><button class="btn secondary" data-reveal="${n}">💡 Speaking tips</button></div><div class="callout" data-tip="${n}" hidden><strong>Self-check / Samoocena</strong><label style="display:block;margin-top:8px"><input type="checkbox"> I answered in full sentences / Odpowiadałem/am pełnymi zdaniami.</label><label style="display:block"><input type="checkbox"> I gave a reason or example / Podałem/am powód lub przykład.</label><label style="display:block"><input type="checkbox"> I used the useful language / Użyłem/am przydatnych zwrotów.</label><p style="margin-bottom:0">Next step: repeat the task and improve one sentence.</p></div><div class="callout" data-clock="${n}" hidden></div></article>`).join('');
out.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>{const x=out.querySelector(`[data-tip="${b.dataset.reveal}"]`);x.hidden=!x.hidden;b.textContent=x.hidden?'💡 Speaking tips':'🙈 Hide tips'});
out.querySelectorAll('[data-timer]').forEach(b=>b.onclick=()=>{const x=out.querySelector(`[data-clock="${b.dataset.timer}"]`);x.hidden=false;let n=60;b.disabled=true;x.textContent='60 seconds — start speaking!';const t=setInterval(()=>{n--;x.textContent=n>0?`${n} seconds left… / ${n} sekund…`:'⏰ Time! Now check your three speaking goals.';if(n<=0){clearInterval(t);b.disabled=false}},1000)});
}draw('ALL');}
const timer=setInterval(()=>{if(document.getElementById('speaking')){render();clearInterval(timer)}},250);
})();