(function(){
  'use strict';
  var PASSWORD='Teach2026!';
  var unlocked=false;
  var areas=[
    {icon:'🗣️',title:'Speaking',goal:'Build confidence before accuracy, then improve both.',steps:['Start with a picture, question or real-life situation. Give quiet thinking time before anyone speaks.','Model one useful answer and display a short sentence frame. Students rehearse in pairs before sharing with the class.','Repeat the task with a new partner, adding one challenge: a reason, detail, follow-up question or more precise word.'],explain:'Explain a speaking point with I do → we do → you do. Say the model aloud, notice one feature, practise it together, then let students use it independently.',check:'Listen for one target at a time. Give feedback as “Two strengths + one next step,” not a list of every error.',adapt:'A1–A2: visuals, word banks and short frames. B1–B2: reasons, comparisons and follow-up questions. C1–C2: nuance, register, evidence and spontaneous reformulation.'},
    {icon:'🎧',title:'Listening',goal:'Teach learners how to listen, not only how to get answers.',steps:['Before listening, activate the topic and predict likely words or ideas. Set one clear purpose.','First listen: gist only. Second listen: details. Third listen: notice useful language, pronunciation or speaker attitude.','Let students compare answers and point to the words or clues that helped them.'],explain:'Make the thinking visible: “I heard ___, so I infer ___.” Replay short sections and model how stress, linking and context carry meaning.',check:'Ask for evidence, not only the answer. Finish with a brief retell, note-taking task or response to the message.',adapt:'A1–A2: short clips, pictures and repeated key words. B1–B2: note-taking and implied meaning. C1–C2: stance, bias, humour, accent variation and fine detail.'},
    {icon:'✍️',title:'Writing',goal:'Treat writing as a process: ideas, structure, language, revision.',steps:['Study a short model from the student tab. Identify audience, purpose, structure and useful language.','Plan together, then co-write one paragraph while talking through the choices. Students draft their own version.','Use a small checklist for revision. Separate meaning and organisation feedback from spelling and grammar correction.'],explain:'Use colour coding to show how a text works: opening, main idea, evidence/detail, linking and ending. Explain why each part helps the reader.',check:'Use a single clear success criterion for each draft. Ask the learner to highlight where they met it and choose one sentence to improve.',adapt:'A1–A2: sentence ordering, frames and short messages. B1–B2: paragraph unity, linking and genre. C1–C2: voice, precision, argument, cohesion and editing for effect.'},
    {icon:'📖',title:'Reading',goal:'Move from understanding the text to explaining how meaning was found.',steps:['Preview the title, images and key words. Ask students to predict the text type and content.','Read once for gist, again for specific information, then closely for language, inference or organisation.','Students justify answers with a phrase from the text and respond through discussion, summary or a short written task.'],explain:'Model a think-aloud: predict, question, clarify, connect and summarise. Show that strong readers repair confusion instead of reading every word at one speed.',check:'Use one literal, one inference and one response question. Ask: “Which words made you think that?”',adapt:'A1–A2: chunked text, visuals and matching. B1–B2: skimming, scanning and inference. C1–C2: rhetoric, viewpoint, credibility, ambiguity and intertextual links.'},
    {icon:'🧩',title:'Grammar',goal:'Connect form, meaning and use so grammar improves communication.',steps:['Begin with examples from the lesson, text or conversation. Learners notice a pattern before the rule is named.','Clarify meaning first, then form and pronunciation. Check with simple contrasting situations.','Practise briefly with control, then use the grammar in a personal speaking or writing task.'],explain:'Avoid rule-only teaching. Use a timeline, contrast, gesture or two example situations, then ask concept-check questions that cannot be answered by repeating the rule.',check:'Use an exit sentence connected to the learner’s life. Correct by prompting: repeat the error, point to the time clue, or offer two choices.',adapt:'A1–A2: one pattern at a time with concrete examples. B1–B2: contrast similar forms and discuss choice. C1–C2: register, emphasis, exceptions and deliberate stylistic use.'},
    {icon:'🧠',title:'Vocabulary',goal:'Teach words as usable networks, not isolated translations.',steps:['Present new language in context from the student material. Include meaning, pronunciation, spelling and common partners.','Students sort, match, personalise and retrieve the words without looking. Recycle them later in the lesson and across the week.','Move from recognition to production through mini-dialogues, stories, explanations or problem-solving.'],explain:'For each item, teach a student-friendly meaning, one clear example, a non-example when useful, word partners and where/when people use it.',check:'Use quick retrieval: “Give the word,” “Use it with…,” “What is the opposite?” or “Which word fits this situation?”',adapt:'A1–A2: high-frequency words, images and chunks. B1–B2: collocations, word families and phrasal verbs. C1–C2: connotation, idiom, register and precise near-synonyms.'}
  ];
  var levelData=[
    ['A1','Survival communication','Model heavily; use real objects, images, gestures and short repeated routines. Keep instructions one step at a time.'],
    ['A2','Everyday independence','Use familiar situations, supported pair work and short connected speech or writing. Add choice without removing scaffolds too quickly.'],
    ['B1','Connected communication','Set practical problems and personal topics. Expect reasons, examples and repair strategies when communication breaks down.'],
    ['B2','Flexible communication','Use authentic input, discussion and genre-based tasks. Push precision, interaction and alternative ways to express an idea.'],
    ['C1','Purposeful, nuanced language','Teach stance, register, synthesis and language choice. Use debate, inquiry and extended texts with independent revision.'],
    ['C2','Control, subtlety and style','Analyse effect, implication and voice. Invite learners to reshape language for different audiences, purposes and identities.']
  ];
  function css(){var s=document.createElement('style');s.textContent=`
  #eeTeacherBtn{position:fixed;right:18px;bottom:18px;z-index:2147483000;border:0;border-radius:999px;padding:13px 18px;background:#183153;color:#fff;font:700 14px/1 system-ui;box-shadow:0 8px 24px #0003;cursor:pointer}
  #eeTeacherBtn:hover{background:#254a78;transform:translateY(-1px)}
  #eeTeacherModal{position:fixed;inset:0;z-index:2147483001;background:#f6f8fb;color:#172033;font-family:Inter,system-ui,sans-serif;overflow:auto}
  .et-top{position:sticky;top:0;z-index:2;background:#183153;color:#fff;padding:16px 5vw;display:flex;gap:16px;align-items:center;box-shadow:0 2px 12px #0002}.et-top h1{font-size:20px;margin:0;flex:1}.et-close,.et-lock{border:1px solid #ffffff66;background:#ffffff14;color:white;border-radius:9px;padding:9px 12px;cursor:pointer}.et-wrap{max-width:1120px;margin:auto;padding:34px 24px 70px}.et-hero{background:linear-gradient(135deg,#e8f2ff,#fff4dc);border-radius:20px;padding:28px;margin-bottom:24px}.et-hero h2{margin:0 0 8px;font-size:30px}.et-hero p{font-size:17px;line-height:1.6;margin:0;max-width:850px}.et-note{margin-top:18px;padding:14px 16px;background:white;border-left:5px solid #ef9f27;border-radius:8px}.et-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:18px}.et-card{background:#fff;border:1px solid #dde4ee;border-radius:16px;padding:22px;box-shadow:0 5px 16px #1831530c}.et-card h3{margin:0 0 6px;font-size:22px}.et-goal{color:#3b5575;font-weight:650;margin:0 0 16px}.et-card h4{font-size:13px;text-transform:uppercase;letter-spacing:.06em;color:#42668e;margin:17px 0 7px}.et-card p,.et-card li{line-height:1.55}.et-card ol{padding-left:21px;margin:0}.et-levels{margin-top:30px}.et-levels h2{font-size:25px}.et-level{display:grid;grid-template-columns:60px 190px 1fr;gap:14px;background:white;border:1px solid #dde4ee;border-radius:12px;padding:14px 16px;margin:9px 0;align-items:start}.et-badge{background:#183153;color:#fff;text-align:center;padding:7px;border-radius:8px;font-weight:800}.et-routine{margin-top:30px;background:#183153;color:white;border-radius:18px;padding:25px}.et-routine ol{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;list-style:none;padding:0;counter-reset:x}.et-routine li{background:#ffffff13;border-radius:12px;padding:14px;counter-increment:x}.et-routine li:before{content:counter(x);display:block;font-size:24px;font-weight:800;color:#ffd37d;margin-bottom:6px}
  .et-login{min-height:100%;display:grid;place-items:center;padding:24px}.et-loginbox{width:min(410px,100%);background:#fff;padding:30px;border-radius:18px;box-shadow:0 12px 40px #18315322;text-align:center}.et-loginbox h2{font-size:28px;margin:5px}.et-loginbox p{color:#54657c;line-height:1.5}.et-loginbox input{width:100%;box-sizing:border-box;padding:13px;border:1px solid #b8c4d3;border-radius:9px;font-size:16px;margin:12px 0}.et-loginbox button{width:100%;border:0;border-radius:9px;padding:13px;background:#183153;color:white;font-weight:750;cursor:pointer}.et-error{color:#b31d28;min-height:20px;margin-top:8px;font-size:14px}@media(max-width:700px){.et-level{grid-template-columns:55px 1fr}.et-level span:last-child{grid-column:1/-1}.et-routine ol{grid-template-columns:1fr}.et-top{padding:13px}.et-top h1{font-size:16px}.et-wrap{padding:22px 14px 60px}.et-hero h2{font-size:24px}}
  `;document.head.appendChild(s)}
  function lockView(){document.getElementById('eeTeacherModal').innerHTML='<div class="et-login"><div class="et-loginbox"><div style="font-size:42px">🔐</div><h2>Teacher Area</h2><p>Teaching guidance for all student skills and levels.</p><input id="etPass" type="password" autocomplete="current-password" placeholder="Teacher password"><button id="etEnter">Open teacher area</button><div class="et-error" id="etError"></div><p style="font-size:12px">Light shared-password protection. Do not store private student information here.</p></div></div>';var inp=document.getElementById('etPass');function go(){if(inp.value===PASSWORD){unlocked=true;guideView()}else{document.getElementById('etError').textContent='That password is not correct.';inp.select()}}document.getElementById('etEnter').onclick=go;inp.onkeydown=function(e){if(e.key==='Enter')go()};setTimeout(function(){inp.focus()},30)}
  function guideView(){var cards=areas.map(function(a){return `<article class="et-card"><h3>${a.icon} ${a.title}</h3><p class="et-goal">${a.goal}</p><h4>How to teach it</h4><ol>${a.steps.map(function(x){return '<li>'+x+'</li>'}).join('')}</ol><h4>Explain it clearly</h4><p>${a.explain}</p><h4>Check learning</h4><p>${a.check}</p><h4>Adjust by level</h4><p>${a.adapt}</p></article>`}).join('');var levels=levelData.map(function(l){return `<div class="et-level"><span class="et-badge">${l[0]}</span><strong>${l[1]}</strong><span>${l[2]}</span></div>`}).join('');document.getElementById('eeTeacherModal').innerHTML=`<header class="et-top"><h1>WordBloom · Teacher Area</h1><button class="et-lock" id="etLock">Lock</button><button class="et-close" id="etClose">Close ×</button></header><main class="et-wrap"><section class="et-hero"><h2>Teach from the student material</h2><p>Use the same Speaking, Listening, Writing, Reading, Grammar and Vocabulary content students see. The teacher layer below turns each item into a clear lesson: activate what learners know, model the thinking, practise with support, use it independently, then reflect.</p><div class="et-note"><strong>PYP / inquiry lens:</strong> begin with a real question or context, invite learners to notice and wonder, make room for choice and collaboration, and end with reflection or action. Language is the tool for inquiry, not a worksheet completed in isolation.</div></section><section class="et-grid">${cards}</section><section class="et-levels"><h2>A1–C2 progression</h2>${levels}</section><section class="et-routine"><h2>A repeatable lesson routine</h2><ol><li><strong>Connect</strong><br>Activate experience, curiosity and prior language.</li><li><strong>Notice</strong><br>Explore a model from the student tab.</li><li><strong>Explain</strong><br>Make one language or strategy point clear.</li><li><strong>Use</strong><br>Apply it in purposeful speaking or writing.</li><li><strong>Reflect</strong><br>Name progress and choose the next step.</li></ol></section></main>`;document.getElementById('etClose').onclick=close;document.getElementById('etLock').onclick=function(){unlocked=false;lockView()}}
  function open(){var m=document.getElementById('eeTeacherModal');if(!m){m=document.createElement('section');m.id='eeTeacherModal';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');document.body.appendChild(m)}m.style.display='block';document.documentElement.style.overflow='hidden';if(unlocked)guideView();else lockView()}
  function close(){var m=document.getElementById('eeTeacherModal');if(m)m.style.display='none';document.documentElement.style.overflow='';}
  function init(){css();var b=document.createElement('button');b.id='eeTeacherBtn';b.textContent='Teacher Area';b.setAttribute('aria-label','Open teacher area');b.onclick=open;document.body.appendChild(b)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
