(function(){
  const LESSONS = [
    {level:'A1',title:'A Morning at Home',type:'Everyday reading',goal:'Read for simple details and sequence.',text:'Emma gets up at seven o’clock. She has breakfast with her family and then gets dressed. At eight o’clock, she leaves home and walks to school. She likes walking because her school is near her house.',pre:['What time do you usually get up?','How do you travel to school or work?'],tasks:[['What time does Emma get up?','7:00','8:00','9:00'],['Why does she like walking?','Her school is near.','She has no bus.','She likes running.']],answers:['A','A'],vocab:'get up • get dressed • leave home • near',follow:'Describe your morning in 4–5 simple sentences.',extension:'Ask a partner three questions about their morning.'},
    {level:'A2',title:'Learning on the Bus',type:'Information reading',goal:'Find the main idea and specific information.',text:'Kasia spends twenty minutes on the bus every morning. Instead of looking at social media, she reviews English words on her phone. She usually studies ten new words and checks them again on the way home. After a few weeks, she notices that she remembers more vocabulary.',pre:['How can you use travel time?','What helps you remember new words?'],tasks:[['What does Kasia do on the bus?','She reviews English words.','She watches films.','She talks to friends.'],['What happens after a few weeks?','She travels less.','She remembers more vocabulary.','She stops using her phone.']],answers:['A','B'],vocab:'review • vocabulary • remember • instead of',follow:'Tell a partner how you could use 15–20 minutes for English practice.',extension:'Write three ideas for learning English during a journey.'},
    {level:'B1',title:'Why Short Breaks Help',type:'Information reading',goal:'Identify the main point and supporting reasons.',text:'Long periods of study can make it difficult to stay focused. Short, planned breaks can help learners return to a task with more energy. A break does not have to be long: standing up, getting some water or looking away from a screen for a few minutes may be enough. The important point is to return to the task rather than allowing a short break to become a long distraction.',pre:['What makes it difficult to concentrate?','What do you normally do during a break?'],tasks:[['What is the main idea?','Long study is always better.','Short planned breaks can support concentration.','Students should study less.'],['What warning does the writer give?','Breaks should never happen.','A break can become a distraction.','Water is unhealthy.']],answers:['B','B'],vocab:'focused • planned • distraction • concentration',follow:'Discuss: What makes a study break useful or unhelpful?',extension:'Paraphrase the main idea in one sentence without using the word “break”.'},
    {level:'B2',title:'Four-Day Working Week',type:'Ideas & opinions',goal:'Recognise an argument, evidence and a condition.',text:'A four-day working week is becoming a serious topic of discussion. Supporters argue that employees may be more productive when they have an extra day to rest, while companies could benefit from better motivation and retention. Critics, however, point out that not every job can be organised around fewer working days. A successful model may therefore depend on the industry, the type of work and whether working hours are compressed.',pre:['Would you prefer four longer days or five shorter days?','What jobs could not easily use a four-day week?'],tasks:[['What is one argument in favour?','Employees may be more productive.','All jobs become easier.','Companies need fewer workers.'],['What does “may” show in the argument?','Certainty','Possibility','A past event'],['What does the final sentence suggest?','One model will suit every workplace.','Success depends on circumstances.','Working hours should disappear.']],answers:['A','B','B'],vocab:'supporter • critic • productive • retention • compressed',follow:'Mini-debate: Four-day working week — good idea or bad idea?',extension:'Write one argument for and one against, then add a condition to your stronger argument.'},
    {level:'C1',title:'Sleep and Performance',type:'Critical information',goal:'Distinguish a general claim from qualification and evidence.',text:'Sleep is often discussed as if a fixed number of hours were ideal for everyone. In reality, individual needs vary, and sleep quality matters alongside duration. Research consistently links insufficient sleep with poorer attention and decision-making, but the relationship is not simply a matter of counting hours. A practical approach is to consider regularity, daytime functioning and individual circumstances rather than relying on one universal target.',pre:['Why might two people need different amounts of sleep?','What signs suggest that someone is not sleeping well?'],tasks:[['Why does the writer reject one universal target?','Sleep needs vary.','Research is unavailable.','People dislike routines.'],['Which factors does the writer recommend considering?','Only total hours','Regularity, daytime functioning and circumstances','Only bedtime'],['What is the tone of the passage?','Overly emotional','Carefully qualified','Humorous']],answers:['A','B','B'],vocab:'duration • insufficient • consistently • regularity • universal',follow:'Explain the writer’s main point in your own words.',extension:'Find one statement in the text that is cautious rather than absolute and explain why.'},
    {level:'C2',title:'Evaluating Evidence',type:'Critical reading',goal:'Evaluate claims, limitations and alternative explanations.',text:'A persuasive claim is not necessarily a well-supported claim. When evaluating evidence, readers should ask whether the evidence is relevant to the conclusion, whether the sample or method is appropriate, and whether alternative explanations have been considered. A single striking result may attract attention without establishing a reliable pattern. Strong critical reading therefore requires more than identifying information: it requires testing the connection between evidence and the conclusion being presented.',pre:['What makes evidence convincing?','Can one example prove a general claim? Why not?'],tasks:[['What is the central distinction?','Interesting claims are always true.','Persuasive claims are not automatically well-supported.','Evidence is unnecessary.'],['Which question is relevant when evaluating evidence?','Is the evidence relevant to the conclusion?','Is the result surprising?','Is the claim popular?'],['What does “alternative explanations” mean here?','Different possible reasons for the result','Different writing styles','Different conclusions already proven']],answers:['B','A','A'],vocab:'persuasive • relevant • sample • reliable • alternative explanation',follow:'Evaluate this claim: “Students who listen to music always learn faster.” What evidence would you want?',extension:'Create a claim about learning and list two pieces of evidence you would need before accepting it.'}
  ];

  function render(){
    const host=document.getElementById('teacher'); if(!host)return;
    if(document.getElementById('teacher-reading-bank'))return;
    const wrap=document.createElement('div'); wrap.id='teacher-reading-bank';
    wrap.innerHTML=`<div class="callout" style="margin-top:24px"><strong>📖 Reading Classroom Bank</strong><br>Ready-to-use reading examples for lessons, with questions, vocabulary, answer keys and follow-up activities.</div><div class="filters" id="trf"></div><div id="trbank" class="grid"></div>`;
    host.appendChild(wrap);
    const filters=wrap.querySelector('#trf'), bank=wrap.querySelector('#trbank');
    ['ALL','A1','A2','B1','B2','C1','C2'].forEach((l,i)=>{const b=document.createElement('button');b.className='choice'+(i===0?' active':'');b.textContent=l;b.onclick=()=>{filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(l)};filters.appendChild(b)});
    function draw(level){bank.innerHTML=LESSONS.filter(x=>level==='ALL'||x.level===level).map((x,idx)=>`<article class="card"><div class="tag">${x.level} • ${x.type}</div><h2>${x.title}</h2><p><strong>Lesson goal:</strong> ${x.goal}</p><h3>Before reading</h3><ol>${x.pre.map(q=>`<li>${q}</li>`).join('')}</ol><h3>Reading text</h3><div class="readtext">${x.text}</div><h3>Tasks</h3>${x.tasks.map((q,i)=>`<div class="answer"><strong>${i+1}. ${q[0]}</strong><div class="choices">${q.slice(1).map((o,j)=>`<label><input type="radio" name="tr${idx}-${i}" value="${String.fromCharCode(65+j)}"> ${String.fromCharCode(65+j)}. ${o}</label>`).join('')}</div></div>`).join('')}<button class="choice" onclick="this.nextElementSibling.hidden=!this.nextElementSibling.hidden">Show answer key</button><div class="callout" hidden><strong>Answers:</strong> ${x.answers.join(' • ')}</div><h3>Key vocabulary</h3><p>${x.vocab}</p><h3>Speaking follow-up</h3><p>${x.follow}</p><h3>Extension</h3><p>${x.extension}</p></article>`).join('')}
    draw('ALL');
  }
  const timer=setInterval(()=>{if(document.getElementById('teacher')){render();clearInterval(timer)}},300);
})();